name: Dep-scan Action
on:
  push:
    branches:
      - main

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    name: Check dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: AppThreat/dep-scan-action@master
        env:
          VDB_HOME: ${{ github.workspace }}/db
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FETCH_LICENSE: true
      - uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports
